version: '3'
services:
  database:
    container_name: postgres_ee
    image: postgres:latest
    env_file: test_database_setup.cfg
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
