version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: Obtain repo from Github
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml --force
            conda activate general_python
      # Step 3: run linter tests
      - run:
          name: run tests
          command:
            conda activate general_python
            flake8
            pytest -v --cov=CalculatorLibrary
